title: FAQ
description: A starter template for a Jeykll site using the Just the Docs theme!
# theme: just-the-docs
remote_theme: "pmarsceill/just-the-docs"
url: https://suss-vli.github.io/

aux_links:
  VLI: http://suss-vli.github.io
