title: FAQ
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://suss-vli.github.io/f

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
