# .github/workflows/git-sync.yml

on:
  push:
    branches:
      - dev

jobs:
  git-sync:
    if: github.repository == 'suss-vli/faq'
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://suss-su:${{ secrets.GITHUBPAT }}@github.com/suss-vli/faq.git"
          source_branch: "dev"
          destination_repo: "https://suss-su:${{ secrets.GITHUBPAT }}@github.com/suss-vli/faq-preview.git"
          destination_branch: "dev"